// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface RateResponse {
  success: boolean;
  base: string;
  date: string;
  rates: Rates;
}

export interface Rates {
  ARS: number;
  CLP: number;
  COP: number;
  EUR: number;
  USD: number;
}
