// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface RateResponse {
  success:    boolean;
  timeseries: boolean;
  base:       string;
  start_date: string;
  end_date:   string;
  rates:      { [key: string]: Rate };
}

export interface Rate {
  ARS: number;
  CLP: number;
  COP: number;
  EUR: number;
  USD: number;
}